### ISSUE TITLE
Is it possible to make the media quality configuration support Chinese？

### ISSUE THREAD

**Issue by kristianvmd** [Feramance/qBitrr#26]
Chinese characters, parentheses, and spaces in media quality profile names seem to cause errors

```tomlkit.exceptions.ParseError: TOML parse error at line 62 col 0```

**Comment by Feramance** [comment]
Could you kindly send your config via pastebin or similar?

**Comment by kristianvmd** [comment]
I've solved it, just need to add " before and after the quality configuration name in Chinese, thanks for your reply!

But there is another problem, I tried to limit the types of files that sonarr can download by configuring FileExtensionAllowlist

I set it up like this-
"FileExtensionAllowlist = [".mp4", ".mkv", ".sub", ".ass", ".srt", ". !qB", ".parts"]"

But it doesn't seem to limit the types of files that can be downloaded, like this link:https://www.tleechreload.org/torrent/241055854

The filenames contained within are:
ghosts.of.beirut.s01e02.hdr.2160p.web.h265-ggwp.r00
ghosts.of.beirut.s01e02.hdr.2160p.web.h265-ggwp.r01
ghosts.of.beirut.s01e02.hdr.2160p.web.h265-ggwp.r02

But it seems sonarr can still download these

**Comment by Feramance** [comment]
Will be adding handling the `FileExtensionAllowlist` in regex format, that way you can add `".r[0-9]*"` to handle those file extensions

**Comment by kristianvmd** [comment]
Sorry I don't quite understand, but isn't FileExtensionAllowlist already restricted to download only [".mp4", ".mkv", ".sub", ".ass", ".srt", ". !qB", ".parts"], why add ".r[0-9]{2}", according to my understanding, adding ".r[0-9]{2}" will not allow them to download?

**Comment by Feramance** [comment]
Your issue is that qBitrr is you want to allow the files you listed to download but it's blocking them? Or you don't want them and it isn't blocking them?

**Comment by kristianvmd** [comment]
i don't want them and it isn't blocking them?

**Comment by Feramance** [comment]
New patch available that should fix it v3.7.8, please confirm

**Comment by Feramance** [comment]
Keep in mind the torrent will still be picked up as the script can only read the files the torrent is attempting to download, it then disallows qbittorrent from downloading them and if those are the only files in the torrent then it-deletes the torrent as a whole thereafter

**Comment by kristianvmd** [comment]
OK, by the way, how soon will the docker version be updated, I'll test it out

**Comment by Feramance** [comment]
The docker version is automatically updated with the release

**Comment by kristianvmd** [comment]
I tested it today and it still doesn't seem to be working, maybe it's my configuration, I made a copy of my system environment and configuration file, can I trouble you to look at it for me, thank you!

qbittorrent version: 4.5.2
qbitrr installation environment: docker
sonarr version: 4.0.0.688-Oct 1 2023


My docker installation command:
docker run -d \
  --name=qbitrr \
 -e TZ=Asia/Shanghai \
  -e RESTART_TIMER=0 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /mnt/sda/appdata/qbitrr:/config \
  -v /mnt/sda/appdata/sonarr/sonarr.db:/databases/sonarr.db:ro \
  -v /mnt/sda/appdata/radarr/radarr.db:/databases/radarr.db:ro \ \
  -v /mnt/sda/media/downloads:/completed_downloads:rw \
  --restart unless-stopped \
  feramance/qbitrr

Here is my config file, I deleted the information about apikey.

```
# This is a config file for the qBitrr Script - Make sure to change all entries of "CHANGE_ME".
# This is a config file should be moved to "/config".


[Settings]
# Level of logging; One of CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG, TRACE
ConsoleLevel = "INFO"

# Enable logging to files
Logging = true

# Folder where your completed downloads are put into. Can be found in qBitTorrent -> Options -> Downloads -> Default Save Path
CompletedDownloadFolder = "/mnt/sda/media/downloads"

# Time to sleep for if there is no internet (in seconds: 600 = 10 Minutes)
NoInternetSleepTimer = 15

# Time to sleep between reprocessing torrents (in seconds: 600 = 10 Minutes)
LoopSleepTimer = 5

# Add torrents to this category to mark them as failed
FailedCategory = "failed"

# Add torrents to this category to trigger them to be rechecked properly
RecheckCategory = "recheck"

# Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)
# Only applicable to Re-check and failed categories
IgnoreTorrentsYoungerThan = 180

# URL to be pinged to check if you have a valid internet connection
# These will be pinged a **LOT** make sure the service is okay with you sending all the continuous pings.
PingURLS = ["one.one.one.one", "dns.google.com"]

# FFprobe auto updates, binaries are downloaded from https://ffbinaries.com/downloads
# If this is disabled and you want ffprobe to work
# Ensure that you add the ffprobe binary to the folder"/config/qBitManager/ffprobe.exe"
# If no `ffprobe` binary is found in the folder above all ffprobe functionality will be disabled.
# By default this will always be on even if config does not have these key - to disable you need to explicitly set it to `False`
FFprobeAutoUpdate = false


[qBit]
# If this is enable qBitrr can run in a headless mode where it will only process searches.
# If media search is enabled in their individual categories
# This is useful if you use for example Sabnzbd/NZBGet for downloading content but still want the faster media searches provided by qbit
Disabled = false

# qBit WebUI Port - Can be found in Options > Web UI (called "IP Address")
Host = "http://192.168.100.100"

# qBit WebUI Port - Can be found in Options > Web UI (called "Port" on top right corner of the window)
Port = 8085

# qBit WebUI Authentication - Can be found in Options > Web UI > Authentication
UserName = "admin"

# If you set "Bypass authentication on localhost or whitelisted IPs" remove this field.
Password = "adminadmin"


["test"]
# Toggle whether to manage the Servarr instance torrents.
Managed = true

# The URL used to access Servarr interface (if you use a domain enter the domain without a port)
URI = "http://192.168.100.100:8990"

# The Servarr API Key, Can be found it Settings > General > Security
APIKey = "aaaaaaaaaaaaaaaaaaa"

# Category applied by Servarr to torrents in qBitTorrent, can be found in Settings > Download Clients > qBit > Category__Servarr 
Category = "sonarr"

# Toggle whether to send a query to Servarr to search any failed torrents
ReSearch = true

# The Servarr's Import Mode(one of Move, Copy or Hardlink)
# importMode = "Hardlink"

# Timer to call RSSSync (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RssSyncTimer = 5

# Timer to call RefreshDownloads to update the queue. (In minutes) - Set to 0 to disable (Values below 5 can cause errors for maximum retires)
RefreshDownloadsTimer = 1

# Error messages shown my the Arr instance which should be considered failures.
# This entry should be a list, leave it empty if you want to disable this error handling.
# If enabled qBitrr will remove the failed files and tell the Arr instance the download failed
ArrErrorCodesToBlocklist = ["Not a preferred word upgrade for existing episode file(s)", "Unable to determine if file is a sample", "Not an upgrade for existing episode file(s)"]


["test".EntrySearch]
# All these settings depends on SearchMissing being True and access to the Servarr database file.

# Should search for Missing files?
SearchMissing = true

# Should search for specials episodes? (Season 00)
AlsoSearchSpecials = false

# Maximum allowed Searches at any one points (I wouldn't recommend settings this too high)
# Sonarr has a hardcoded cap of 3 simultaneous tasks
SearchLimit = 1

# Servarr Datapath file path
# This is required for any of the search functionality to work
# The only exception for this is the "ReSearch" setting as that is done via an API call.
DatabaseFile = "/databases/sonarr.db"

# It will order searches by the year the EPISODE was first aired
SearchByYear = true

# Reverse search order (Start searching oldest to newest)
SearchInReverse = false

# Delay between request searches in seconds
SearchRequestsEvery = 60

# Search movies which already have a file in the database in hopes of finding a better quality version.
DoUpgradeSearch = false

# Do a quality unmet search for existing entries.
QualityUnmetSearch = false

# Once you have search all files on your specified year range restart the loop and search again.
SearchAgainOnSearchCompletion = true

# Search by series instead of by episode
SearchBySeries = true

# Prioritize Today's releases (Similar effect as RSS Sync, where it searches today's release episodes first, only works on Sonarr).
PrioritizeTodaysReleases = false


["test".EntrySearch.Ombi]
# Search Ombi for pending requests (Will only work if 'SearchMissing' is enabled.)
SearchOmbiRequests = false

# Ombi URI (Note that this has to be the instance of Ombi which manage the Arr instance request (If you have multiple Ombi instances)
OmbiURI = "CHANGE_ME"

# Ombi's API Key
OmbiAPIKey = "CHANGE_ME"

# Only process approved requests
ApprovedOnly = true


["test".EntrySearch.Overseerr]
# Search Overseerr for pending requests (Will only work if 'SearchMissing' is enabled.)
# If this and Ombi are both enable, Ombi will be ignored
SearchOverseerrRequests = false

# Overseerr's URI
OverseerrURI = "http://192.168.100.100:5059"

# Overseerr's API Key
# OverseerrAPIKey = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

# Only process approved requests
# ApprovedOnly = true

# Only for 4K Instances
# Is4K = false


["test".Torrent]
# Set it to regex matches to respect/ignore case.
CaseSensitiveMatches = false

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
#FolderExclusionRegex = ["\\bextras?\\b", "\\bfeaturettes?\\b", "\\bsamples?\\b", "\\bscreens?\\b", "\\bnc(ed|op)?(\\\\d+)?\\b"]

# These regex values will match any folder where the full name matches the specified values here, comma separated strings.
# These regex need to be escaped, that's why you see so many backslashes.
#FileNameExclusionRegex = ["\\bncop\\\\d+?\\b", "\\bnced\\\\d+?\\b", "\\bsample\\b", "brarbg.com\\b", "\\btrailer\\b", "music video", "comandotorrents.com"]

# Only files with these extensions will be allowed to be downloaded, comma separated strings, leave it empty to allow all extensions
FileExtensionAllowlist = [".mp4", ".mkv", ".sub", ".ass", ".srt", ".!qB", ".parts"]

# Auto delete files that can't be playable (i.e .exe, .png)_自动删除无法播放的文件（即.exe、.png）
AutoDelete = false

# Ignore Torrents which are younger than this value (in seconds: 600 = 10 Minutes)
#IgnoreTorrentsYoungerThan = 180

# Maximum allowed remaining ETA for torrent completion (in seconds: 3600 = 1 Hour)
# Note that if you set the MaximumETA on a tracker basis that value is favoured over this value
MaximumETA = 604800

# Do not delete torrents with higher completion percentage than this setting (0.5 = 50%, 1.0 = 100%)
MaximumDeletablePercentage = 0.99

# Ignore slow torrents.
DoNotRemoveSlow = true

Trackers = []

["test".Torrent.SeedingMode]
# Set the maximum allowed download rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the DownloadRateLimit on a tracker basis that value is favoured over this value
DownloadRateLimitPerTorrent = -1

# Set the maximum allowed upload rate for torrents
# Set this value to -1 to disabled it
# Note that if you set the UploadRateLimit on a tracker basis that value is favoured over this value
UploadRateLimitPerTorrent = -1

# Set the maximum allowed upload ratio for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxUploadRatio on a tracker basis that value is favoured over this value
MaxUploadRatio = -1

# Set the maximum seeding time in seconds for torrents
# Set this value to -1 to disabled it
# Note that if you set the MaxSeedingTime on a tracker basis that value is favoured over this value
MaxSeedingTime = -1

# Remove torrent condition (-1=Do not remove, 1=Remove on MaxUploadRatio, 2=Remove on MaxSeedingTime, 3=Remove on MaxUploadRatio or MaxSeedingTime, 4=Remove on MaxUploadRatio and MaxSeedingTime) 
#RemoveTorrent = -1

# Enable if you want to remove dead trackers
RemoveDeadTrackers = false

# If "RemoveDeadTrackers" is set to true then remove trackers with the following messages
RemoveTrackerWithMessage = ["skipping tracker announce (unreachable)", "No such host is known", "unsupported URL protocol", "info hash is not authorized with this tracker"]
```

**Comment by kristianvmd** [comment]
Sorry another question, the time zone in the system I'm using is not in -v /etc/localtime, if I just add the variable -e TZ=Asia/Shanghai \ \ Is there a problem?

**Comment by Feramance** [comment]
So time zone is no problem to add. Did you provide the ffprobe binaries yourself to the correct folder? I suggest you use `Sonarr` rather than `"test"`, or at the least `test`. And kindly set your log level to trace, let it run for an hour and send over the log that is generated in the log folder

**Comment by Feramance** [comment]
You also have Autodelete set to false, try setting it to true

**Comment by kristianvmd** [comment]
I have not configured ffprobe binaries, I turned this off with #, does this have to be on.

Also like # importMode = "Hardlink" I chose to turn it off because I set it to auto delete for bt downloads and auto keep for pt downloads.

Do I have to set each of these or can I leave the ones that aren't linked on?

Here's my qbitrr log

```
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] INFO    : qBitrr                      : Starting qBitrr: Version: 3.7.9-be78141.
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] INFO    : qBitrr                      : Restart timer is set to 0 hours
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] INFO    : qBitrr.Manager              : Current qBitTorrent version is supported: 4.5.2
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] ERROR   : qBitrr.ArrManager           : '/config/qBitManager/ffprobe' was not found, disabling all functionality dependant on it
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] HNOTICE : qBitrr.Recheck              : Starting Recheck monitor
[2023-10-10 22:19:21] [pid:       1][tid:140502950202240] HNOTICE : qBitrr.Failed               : Starting Failed monitor
[2023-10-10 22:19:21] [pid:       7][tid:140502950202240] HNOTICE : qBitrr.Recheck              : Starting torrent monitoring for Recheck
[2023-10-10 22:19:21] [pid:       8][tid:140502950202240] HNOTICE : qBitrr.Failed               : Starting torrent monitoring for Failed
```

**Comment by Feramance** [comment]
I will look into that

**Comment by Feramance** [comment]
Can you send me your config with the Chinese characters?

**Comment by kristianvmd** [comment]
[config.zip](https://github.com/Feramance/qBitrr/files/12904267/config.zip)

Sure，thank you

**Comment by Feramance** [comment]
Can you kindly test using a name like `Sonarr-4K小于30G`?

**Comment by kristianvmd** [comment]
[Desktop.zip](https://github.com/Feramance/qBitrr/files/12937486/Desktop.zip)
Sorry I'm just seeing this now, it still doesn't seem to be working. Here's the log.

**Comment by kristianvmd** [comment]
[config.zip](https://github.com/Feramance/qBitrr/files/12937525/config.zip)
This is the configuration file I use

**Comment by Feramance** [comment]
Upon further investigation, it seems like this is a limitation of the tomlkit from python and nothing much I can really do about that
